#SPDX-License-Identifier: MIT-0
---
# vars file for post-install
mydir: /opt/testdir
USRNM: alluser
COMM: user from group_vars_all
ntp0: 0.europe.pool.ntp.org
ntp1: 1.europe.pool.ntp.org
ntp2: 2.europe.pool.ntp.org
ntp3: 3.europe.pool.ntp.org
